# Generated by Django 5.0.6 on 2024-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='room_images/')),
                ('capacity', models.IntegerField()),
                ('reserve_date', models.DateField()),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('transportation', models.BooleanField(default=False)),
                ('tour_guide', models.BooleanField(default=False)),
            ],
        ),
    ]
