# Generated by Django 5.0.6 on 2024-06-27 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='check_in_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
